<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="61" started-at="2016-05-19T17:42:44Z" finished-at="2016-05-19T17:42:44Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="61" started-at="2016-05-19T17:42:44Z" finished-at="2016-05-19T17:42:44Z">
      <class name="com.thalesgroup.services.cte.lis.dojo.Story1Test">
        <test-method status="PASS" signature="testLastCellOfRow()[pri:0, instance:com.thalesgroup.services.cte.lis.dojo.Story1Test@2d6a9952]" name="testLastCellOfRow" duration-ms="28" started-at="2016-05-19T19:42:44Z" finished-at="2016-05-19T19:42:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLastCellOfRow -->
      </class> <!-- com.thalesgroup.services.cte.lis.dojo.Story1Test -->
      <class name="com.thalesgroup.services.cte.lis.dojo.Story3Test">
        <test-method status="PASS" signature="testLastCellOfRow()[pri:0, instance:com.thalesgroup.services.cte.lis.dojo.Story3Test@1bc6a36e]" name="testLastCellOfRow" duration-ms="5" started-at="2016-05-19T19:42:44Z" finished-at="2016-05-19T19:42:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLastCellOfRow -->
      </class> <!-- com.thalesgroup.services.cte.lis.dojo.Story3Test -->
      <class name="com.thalesgroup.services.cte.lis.dojo.Story2Test">
        <test-method status="PASS" signature="testLastCellOfRow()[pri:0, instance:com.thalesgroup.services.cte.lis.dojo.Story2Test@629f0666]" name="testLastCellOfRow" duration-ms="5" started-at="2016-05-19T19:42:44Z" finished-at="2016-05-19T19:42:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLastCellOfRow -->
      </class> <!-- com.thalesgroup.services.cte.lis.dojo.Story2Test -->
      <class name="com.thalesgroup.services.cte.lis.dojo.Story4Test">
        <test-method status="FAIL" signature="testLastCellOfRow()[pri:0, instance:com.thalesgroup.services.cte.lis.dojo.Story4Test@1ff8b8f]" name="testLastCellOfRow" duration-ms="7" started-at="2016-05-19T19:42:44Z" finished-at="2016-05-19T19:42:44Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected value '5' in cell (row=4,column=6) but obtained value '0' instead.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected value '5' in cell (row=4,column=6) but obtained value '0' instead.
	at org.testng.Assert.fail(Assert.java:94)
	at com.thalesgroup.services.cte.lis.dojo.SudokuTest$SolvedProblem$CellChecker.shallContain(SudokuTest.java:64)
	at com.thalesgroup.services.cte.lis.dojo.Story4Test.testLastCellOfRow(Story4Test.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLastCellOfRow -->
      </class> <!-- com.thalesgroup.services.cte.lis.dojo.Story4Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
